const conjugationData = {
  être: {
    present: {
      je: "suis",
      tu: "es",
      il: "est",
      nous: "sommes",
      vous: "êtes",
      ils: "sont",
    },
    imparfait: {
      je: "étais",
      tu: "étais",
      il: "était",
      nous: "étions",
      vous: "étiez",
      ils: "étaient",
    },
    futur: {
      je: "serai",
      tu: "seras",
      il: "sera",
      nous: "serons",
      vous: "serez",
      ils: "seront",
    },
  },
  avoir: {
    present: {
      je: "ai",
      tu: "as",
      il: "a",
      nous: "avons",
      vous: "avez",
      ils: "ont",
    },
    imparfait: {
      je: "avais",
      tu: "avais",
      il: "avait",
      nous: "avions",
      vous: "aviez",
      ils: "avaient",
    },
    futur: {
      je: "aurai",
      tu: "auras",
      il: "aura",
      nous: "aurons",
      vous: "aurez",
      ils: "auront",
    },
  },
  faire: {
    present: {
      je: "fais",
      tu: "fais",
      il: "fait",
      nous: "faisons",
      vous: "faites",
      ils: "font",
    },
    imparfait: {
      je: "faisais",
      tu: "faisais",
      il: "faisait",
      nous: "faisions",
      vous: "faisiez",
      ils: "faisaient",
    },
    futur: {
      je: "ferai",
      tu: "feras",
      il: "fera",
      nous: "ferons",
      vous: "ferez",
      ils: "feront",
    },
  },
  aller: {
    present: {
      je: "vais",
      tu: "vas",
      il: "va",
      nous: "allons",
      vous: "allez",
      ils: "vont",
    },
    imparfait: {
      je: "allais",
      tu: "allais",
      il: "allait",
      nous: "allions",
      vous: "alliez",
      ils: "allaient",
    },
    futur: {
      je: "irai",
      tu: "iras",
      il: "ira",
      nous: "irons",
      vous: "irez",
      ils: "iront",
    },
  },
  venir: {
    present: {
      je: "viens",
      tu: "viens",
      il: "vient",
      nous: "venons",
      vous: "venez",
      ils: "viennent",
    },
    imparfait: {
      je: "venais",
      tu: "venais",
      il: "venait",
      nous: "venions",
      vous: "veniez",
      ils: "venaient",
    },
    futur: {
      je: "viendrai",
      tu: "viendras",
      il: "viendra",
      nous: "viendrons",
      vous: "viendrez",
      ils: "viendront",
    },
  },
  prendre: {
    present: {
      je: "prends",
      tu: "prends",
      il: "prend",
      nous: "prenons",
      vous: "prenez",
      ils: "prennent",
    },
    imparfait: {
      je: "prenais",
      tu: "prenais",
      il: "prenait",
      nous: "prenions",
      vous: "preniez",
      ils: "prenaient",
    },
    futur: {
      je: "prendrai",
      tu: "prendras",
      il: "prendra",
      nous: "prendrons",
      vous: "prendrez",
      ils: "prendront",
    },
  },
  pouvoir: {
    present: {
      je: "peux",
      tu: "peux",
      il: "peut",
      nous: "pouvons",
      vous: "pouvez",
      ils: "peuvent",
    },
    imparfait: {
      je: "pouvais",
      tu: "pouvais",
      il: "pouvait",
      nous: "pouvions",
      vous: "pouviez",
      ils: "pouvaient",
    },
    futur: {
      je: "pourrai",
      tu: "pourras",
      il: "pourra",
      nous: "pourrons",
      vous: "pourrez",
      ils: "pourront",
    },
  },
  vouloir: {
    present: {
      je: "veux",
      tu: "veux",
      il: "veut",
      nous: "voulons",
      vous: "voulez",
      ils: "veulent",
    },
    imparfait: {
      je: "voulais",
      tu: "voulais",
      il: "voulait",
      nous: "voulions",
      vous: "vouliez",
      ils: "voulaient",
    },
    futur: {
      je: "voudrai",
      tu: "voudras",
      il: "voudra",
      nous: "voudrons",
      vous: "voudrez",
      ils: "voudront",
    },
  },
  devoir: {
    present: {
      je: "dois",
      tu: "dois",
      il: "doit",
      nous: "devons",
      vous: "devez",
      ils: "doivent",
    },
    imparfait: {
      je: "devais",
      tu: "devais",
      il: "devait",
      nous: "devions",
      vous: "deviez",
      ils: "devaient",
    },
    futur: {
      je: "devrai",
      tu: "devras",
      il: "devra",
      nous: "devrons",
      vous: "devrez",
      ils: "devront",
    },
  },
  dire: {
    present: {
      je: "dis",
      tu: "dis",
      il: "dit",
      nous: "disons",
      vous: "dites",
      ils: "disent",
    },
    imparfait: {
      je: "disais",
      tu: "disais",
      il: "disait",
      nous: "disions",
      vous: "disiez",
      ils: "disaient",
    },
    futur: {
      je: "dirai",
      tu: "diras",
      il: "dira",
      nous: "dirons",
      vous: "direz",
      ils: "diront",
    },
  },
  voir: {
    present: {
      je: "vois",
      tu: "vois",
      il: "voit",
      nous: "voyons",
      vous: "voyez",
      ils: "voient",
    },
    imparfait: {
      je: "voyais",
      tu: "voyais",
      il: "voyait",
      nous: "voyions",
      vous: "voyiez",
      ils: "voyaient",
    },
    futur: {
      je: "verrai",
      tu: "verras",
      il: "verra",
      nous: "verrons",
      vous: "verrez",
      ils: "verront",
    },
  },
  savoir: {
    present: {
      je: "sais",
      tu: "sais",
      il: "sait",
      nous: "savons",
      vous: "savez",
      ils: "savent",
    },
    imparfait: {
      je: "savais",
      tu: "savais",
      il: "savait",
      nous: "savions",
      vous: "saviez",
      ils: "savaient",
    },
    futur: {
      je: "saurai",
      tu: "sauras",
      il: "saura",
      nous: "saurons",
      vous: "saurez",
      ils: "sauront",
    },
  },
  partir: {
    present: {
      je: "pars",
      tu: "pars",
      il: "part",
      nous: "partons",
      vous: "partez",
      ils: "partent",
    },
    imparfait: {
      je: "partais",
      tu: "partais",
      il: "partait",
      nous: "partions",
      vous: "partiez",
      ils: "partaient",
    },
    futur: {
      je: "partirai",
      tu: "partiras",
      il: "partira",
      nous: "partirons",
      vous: "partirez",
      ils: "partiront",
    },
  },
  dormir: {
    present: {
      je: "dors",
      tu: "dors",
      il: "dort",
      nous: "dormons",
      vous: "dormez",
      ils: "dorment",
    },
    imparfait: {
      je: "dormais",
      tu: "dormais",
      il: "dormait",
      nous: "dormions",
      vous: "dormiez",
      ils: "dormaient",
    },
    futur: {
      je: "dormirai",
      tu: "dormiras",
      il: "dormira",
      nous: "dormirons",
      vous: "dormirez",
      ils: "dormiront",
    },
  },
  sortir: {
    present: {
      je: "sors",
      tu: "sors",
      il: "sort",
      nous: "sortons",
      vous: "sortez",
      ils: "sortent",
    },
    imparfait: {
      je: "sortais",
      tu: "sortais",
      il: "sortait",
      nous: "sortions",
      vous: "sortiez",
      ils: "sortaient",
    },
    futur: {
      je: "sortirai",
      tu: "sortiras",
      il: "sortira",
      nous: "sortirons",
      vous: "sortirez",
      ils: "sortiront",
    },
  },
  servir: {
    present: {
      je: "sers",
      tu: "sers",
      il: "sert",
      nous: "servons",
      vous: "servez",
      ils: "servent",
    },
    imparfait: {
      je: "servais",
      tu: "servais",
      il: "servait",
      nous: "servions",
      vous: "serviez",
      ils: "servaient",
    },
    futur: {
      je: "servirai",
      tu: "serviras",
      il: "servira",
      nous: "servirons",
      vous: "servirez",
      ils: "serviront",
    },
  },
};
