const conjugationData = {
  être: {
    present: {
      je: "suis",
      tu: "es",
      "il/elle/on": "est",
      nous: "sommes",
      vous: "êtes",
      "ils/elles": "sont",
    },
    imparfait: {
      je: "étais",
      tu: "étais",
      "il/elle/on": "était",
      nous: "étions",
      vous: "étiez",
      "ils/elles": "étaient",
    },
    futur: {
      je: "serai",
      tu: "seras",
      "il/elle/on": "sera",
      nous: "serons",
      vous: "serez",
      "ils/elles": "seront",
    },
  },
  avoir: {
    present: {
      je: "ai",
      tu: "as",
      "il/elle/on": "a",
      nous: "avons",
      vous: "avez",
      "ils/elles": "ont",
    },
    imparfait: {
      je: "avais",
      tu: "avais",
      "il/elle/on": "avait",
      nous: "avions",
      vous: "aviez",
      "ils/elles": "avaient",
    },
    futur: {
      je: "aurai",
      tu: "auras",
      "il/elle/on": "aura",
      nous: "aurons",
      vous: "aurez",
      "ils/elles": "auront",
    },
  },
  faire: {
    present: {
      je: "fais",
      tu: "fais",
      "il/elle/on": "fait",
      nous: "faisons",
      vous: "faites",
      "ils/elles": "font",
    },
    imparfait: {
      je: "faisais",
      tu: "faisais",
      "il/elle/on": "faisait",
      nous: "faisions",
      vous: "faisiez",
      "ils/elles": "faisaient",
    },
    futur: {
      je: "ferai",
      tu: "feras",
      "il/elle/on": "fera",
      nous: "ferons",
      vous: "ferez",
      "ils/elles": "feront",
    },
  },
  aller: {
    present: {
      je: "vais",
      tu: "vas",
      "il/elle/on": "va",
      nous: "allons",
      vous: "allez",
      "ils/elles": "vont",
    },
    imparfait: {
      je: "allais",
      tu: "allais",
      "il/elle/on": "allait",
      nous: "allions",
      vous: "alliez",
      "ils/elles": "allaient",
    },
    futur: {
      je: "irai",
      tu: "iras",
      "il/elle/on": "ira",
      nous: "irons",
      vous: "irez",
      "ils/elles": "iront",
    },
  },
  venir: {
    present: {
      je: "viens",
      tu: "viens",
      "il/elle/on": "vient",
      nous: "venons",
      vous: "venez",
      "ils/elles": "viennent",
    },
    imparfait: {
      je: "venais",
      tu: "venais",
      "il/elle/on": "venait",
      nous: "venions",
      vous: "veniez",
      "ils/elles": "venaient",
    },
    futur: {
      je: "viendrai",
      tu: "viendras",
      "il/elle/on": "viendra",
      nous: "viendrons",
      vous: "viendrez",
      "ils/elles": "viendront",
    },
  },
};
