const wordCategories = {
  verbs: [
    { french: "être", english: "to be" },
    { french: "avoir", english: "to have" },
    { french: "faire", english: "to do, to make" },
    { french: "aller", english: "to go" },
    { french: "venir", english: "to come" },
    { french: "dire", english: "to say" },
    { french: "voir", english: "to see" },
    { french: "pouvoir", english: "to be able to" },
    { french: "vouloir", english: "to want" },
    { french: "devoir", english: "to have to" },
    { french: "prendre", english: "to take" },
    { french: "donner", english: "to give" },
    { french: "parler", english: "to speak" },
    { french: "manger", english: "to eat" },
    { french: "boire", english: "to drink" },
    { french: "dormir", english: "to sleep" },
    { french: "écrire", english: "to write" },
    { french: "lire", english: "to read" },
    { french: "comprendre", english: "to understand" },
    { french: "apprendre", english: "to learn" },
    { french: "penser", english: "to think" },
    { french: "croire", english: "to believe" },
    { french: "savoir", english: "to know" },
    { french: "connaître", english: "to know, to be familiar with" },
    { french: "vivre", english: "to live" },
    { french: "mourir", english: "to die" },
    { french: "naître", english: "to be born" },
    { french: "grandir", english: "to grow" },
    { french: "vieillir", english: "to grow old" },
    { french: "changer", english: "to change" },
    { french: "commencer", english: "to begin" },
    { french: "finir", english: "to finish" },
    { french: "continuer", english: "to continue" },
    { french: "arrêter", english: "to stop" },
    { french: "attendre", english: "to wait" },
    { french: "chercher", english: "to look for" },
    { french: "trouver", english: "to find" },
    { french: "perdre", english: "to lose" },
    { french: "gagner", english: "to win" },
    { french: "jouer", english: "to play" },
    { french: "travailler", english: "to work" },
    { french: "étudier", english: "to study" },
    { french: "enseigner", english: "to teach" },
    { french: "apprendre", english: "to learn" },
    { french: "oublier", english: "to forget" },
    { french: "se souvenir", english: "to remember" },
    { french: "réfléchir", english: "to think, to reflect" },
    { french: "décider", english: "to decide" },
    { french: "choisir", english: "to choose" },
    { french: "préférer", english: "to prefer" },
    { french: "aimer", english: "to like, to love" },
    { french: "détester", english: "to hate" },
    { french: "espérer", english: "to hope" },
    { french: "souhaiter", english: "to wish" },
    { french: "demander", english: "to ask" },
    { french: "répondre", english: "to answer" },
    { french: "écouter", english: "to listen" },
    { french: "entendre", english: "to hear" },
    { french: "regarder", english: "to watch, to look" },
    { french: "sentir", english: "to feel, to smell" },
    { french: "toucher", english: "to touch" },
    { french: "goûter", english: "to taste" },
    { french: "marcher", english: "to walk" },
    { french: "courir", english: "to run" },
    { french: "sauter", english: "to jump" },
    { french: "nager", english: "to swim" },
    { french: "danser", english: "to dance" },
    { french: "chanter", english: "to sing" },
    { french: "jouer", english: "to play" },
    { french: "voyager", english: "to travel" },
    { french: "visiter", english: "to visit" },
    { french: "habiter", english: "to live (in a place)" },
    { french: "déménager", english: "to move (house)" },
    { french: "construire", english: "to build" },
    { french: "détruire", english: "to destroy" },
    { french: "réparer", english: "to repair" },
    { french: "nettoyer", english: "to clean" },
    { french: "laver", english: "to wash" },
    { french: "cuisiner", english: "to cook" },
    { french: "manger", english: "to eat" },
    { french: "boire", english: "to drink" },
    { french: "fumer", english: "to smoke" },
    { french: "dormir", english: "to sleep" },
    { french: "se réveiller", english: "to wake up" },
    { french: "se coucher", english: "to go to bed" },
    { french: "se lever", english: "to get up" },
    { french: "s'habiller", english: "to get dressed" },
    { french: "se déshabiller", english: "to get undressed" },
    { french: "se brosser", english: "to brush" },
    { french: "se laver", english: "to wash oneself" },
    { french: "se maquiller", english: "to put on makeup" },
    { french: "se raser", english: "to shave" },
    { french: "se peigner", english: "to comb" },
    { french: "se coiffer", english: "to do one's hair" },
    { french: "se reposer", english: "to rest" },
    { french: "se relaxer", english: "to relax" },
    { french: "s'amuser", english: "to have fun" },
    { french: "se promener", english: "to take a walk" },
    { french: "se balader", english: "to stroll" },
    { french: "se dépêcher", english: "to hurry" },
    { french: "s'arrêter", english: "to stop" },
    { french: "se retourner", english: "to turn around" },
    { french: "se tourner", english: "to turn" },
    { french: "se pencher", english: "to lean" },
    { french: "se baisser", english: "to bend down" },
    { french: "se lever", english: "to stand up" },
    { french: "s'asseoir", english: "to sit down" },
    { french: "se coucher", english: "to lie down" },
  ],
  nouns: [
    { french: "la maison", english: "house" },
    { french: "le temps", english: "time, weather" },
    { french: "la vie", english: "life" },
    { french: "le jour", english: "day" },
    { french: "la nuit", english: "night" },
    { french: "l'eau", english: "water" },
    { french: "le pain", english: "bread" },
    { french: "le livre", english: "book" },
    { french: "la voiture", english: "car" },
    { french: "le train", english: "train" },
    { french: "l'avion", english: "airplane" },
    { french: "le téléphone", english: "phone" },
    { french: "l'ordinateur", english: "computer" },
    { french: "la table", english: "table" },
    { french: "la chaise", english: "chair" },
    { french: "la porte", english: "door" },
    { french: "la fenêtre", english: "window" },
    { french: "le lit", english: "bed" },
    { french: "la cuisine", english: "kitchen" },
    { french: "la salle de bain", english: "bathroom" },
    { french: "le jardin", english: "garden" },
    { french: "la rue", english: "street" },
    { french: "la ville", english: "city" },
    { french: "le pays", english: "country" },
    { french: "la mer", english: "sea" },
    { french: "la montagne", english: "mountain" },
    { french: "la forêt", english: "forest" },
    { french: "le soleil", english: "sun" },
    { french: "la lune", english: "moon" },
    { french: "l'étoile", english: "star" },
    { french: "le ciel", english: "sky" },
    { french: "la terre", english: "earth" },
    { french: "l'air", english: "air" },
    { french: "le feu", english: "fire" },
    { french: "la glace", english: "ice" },
    { french: "la neige", english: "snow" },
    { french: "la pluie", english: "rain" },
    { french: "le vent", english: "wind" },
    { french: "la tempête", english: "storm" },
    { french: "l'orage", english: "thunderstorm" },
    { french: "le matin", english: "morning" },
    { french: "l'après-midi", english: "afternoon" },
    { french: "le soir", english: "evening" },
    { french: "la semaine", english: "week" },
    { french: "le mois", english: "month" },
    { french: "l'année", english: "year" },
    { french: "le siècle", english: "century" },
    { french: "l'heure", english: "hour" },
    { french: "la minute", english: "minute" },
    { french: "la seconde", english: "second" },
    { french: "le matin", english: "morning" },
    { french: "le midi", english: "noon" },
    { french: "le soir", english: "evening" },
    { french: "la nuit", english: "night" },
    { french: "l'aube", english: "dawn" },
    { french: "le crépuscule", english: "dusk" },
    { french: "le printemps", english: "spring" },
    { french: "l'été", english: "summer" },
    { french: "l'automne", english: "autumn" },
    { french: "l'hiver", english: "winter" },
    { french: "le père", english: "father" },
    { french: "la mère", english: "mother" },
    { french: "le frère", english: "brother" },
    { french: "la sœur", english: "sister" },
    { french: "le fils", english: "son" },
    { french: "la fille", english: "daughter" },
    { french: "le mari", english: "husband" },
    { french: "la femme", english: "wife" },
    { french: "l'ami", english: "friend" },
    { french: "l'ennemi", english: "enemy" },
    { french: "le voisin", english: "neighbor" },
    { french: "le professeur", english: "teacher" },
    { french: "l'élève", english: "student" },
    { french: "le médecin", english: "doctor" },
    { french: "l'infirmier", english: "nurse" },
    { french: "le policier", english: "police officer" },
    { french: "le pompier", english: "firefighter" },
    { french: "le boulanger", english: "baker" },
    { french: "le boucher", english: "butcher" },
    { french: "le coiffeur", english: "hairdresser" },
    { french: "le jardinier", english: "gardener" },
    { french: "le chauffeur", english: "driver" },
    { french: "le facteur", english: "mailman" },
    { french: "le journaliste", english: "journalist" },
    { french: "l'acteur", english: "actor" },
    { french: "l'actrice", english: "actress" },
    { french: "le musicien", english: "musician" },
    { french: "le peintre", english: "painter" },
    { french: "l'écrivain", english: "writer" },
    { french: "le poète", english: "poet" },
    { french: "le scientifique", english: "scientist" },
    { french: "l'ingénieur", english: "engineer" },
    { french: "l'architecte", english: "architect" },
    { french: "le cuisinier", english: "cook" },
    { french: "le serveur", english: "waiter" },
    { french: "la serveuse", english: "waitress" },
    { french: "le vendeur", english: "salesman" },
    { french: "la vendeuse", english: "saleswoman" },
    { french: "le caissier", english: "cashier" },
  ],
  adjectives: [
    { french: "grand", english: "tall, big" },
    { french: "petit", english: "small" },
    { french: "beau", english: "beautiful" },
    { french: "laid", english: "ugly" },
    { french: "bon", english: "good" },
    { french: "mauvais", english: "bad" },
    { french: "chaud", english: "hot" },
    { french: "froid", english: "cold" },
    { french: "nouveau", english: "new" },
    { french: "vieux", english: "old" },
    { french: "jeune", english: "young" },
    { french: "vieux", english: "old" },
    { french: "riche", english: "rich" },
    { french: "pauvre", english: "poor" },
    { french: "facile", english: "easy" },
    { french: "difficile", english: "difficult" },
    { french: "important", english: "important" },
    { french: "possible", english: "possible" },
    { french: "impossible", english: "impossible" },
    { french: "nécessaire", english: "necessary" },
  ],
  adverbs: [
    { french: "bien", english: "well" },
    { french: "mal", english: "badly" },
    { french: "très", english: "very" },
    { french: "trop", english: "too much" },
    { french: "peu", english: "little" },
    { french: "beaucoup", english: "a lot" },
    { french: "aussi", english: "also" },
    { french: "encore", english: "still, yet" },
    { french: "déjà", english: "already" },
    { french: "toujours", english: "always" },
    { french: "jamais", english: "never" },
    { french: "maintenant", english: "now" },
    { french: "aujourd'hui", english: "today" },
    { french: "demain", english: "tomorrow" },
    { french: "hier", english: "yesterday" },
    { french: "ici", english: "here" },
    { french: "là", english: "there" },
    { french: "partout", english: "everywhere" },
    { french: "quelque part", english: "somewhere" },
    { french: "nulle part", english: "nowhere" },
  ],
  pronouns: [
    { french: "je", english: "I" },
    { french: "tu", english: "you (singular)" },
    { french: "il", english: "he" },
    { french: "elle", english: "she" },
    { french: "nous", english: "we" },
    { french: "vous", english: "you (plural/formal)" },
    { french: "ils", english: "they (masculine)" },
    { french: "elles", english: "they (feminine)" },
    { french: "me", english: "me" },
    { french: "te", english: "you" },
    { french: "le", english: "him, it" },
    { french: "la", english: "her, it" },
    { french: "nous", english: "us" },
    { french: "vous", english: "you" },
    { french: "les", english: "them" },
    { french: "moi", english: "me" },
    { french: "toi", english: "you" },
    { french: "lui", english: "him, her" },
    { french: "eux", english: "them" },
    { french: "soi", english: "oneself" },
  ],
  prepositions: [
    { french: "à", english: "to, at" },
    { french: "de", english: "of, from" },
    { french: "en", english: "in, by" },
    { french: "sur", english: "on" },
    { french: "sous", english: "under" },
    { french: "dans", english: "in" },
    { french: "avec", english: "with" },
    { french: "sans", english: "without" },
    { french: "pour", english: "for" },
    { french: "par", english: "by" },
    { french: "contre", english: "against" },
    { french: "entre", english: "between" },
    { french: "devant", english: "in front of" },
    { french: "derrière", english: "behind" },
    { french: "près de", english: "near" },
    { french: "loin de", english: "far from" },
    { french: "avant", english: "before" },
    { french: "après", english: "after" },
    { french: "pendant", english: "during" },
    { french: "depuis", english: "since" },
  ],
};
